### ISSUE TITLE
research paper

### ISSUE THREAD

**Issue by advocs** [HoangNV2001/Real-time-IDS#1]
can u please share the research paper for this topic so that we can go through the details of this project.

**Comment by HoangNV2001** [comment]
Sorry for the late response. 

This was a course project. Unfortunately, I cannot share the report. However, I can share with you some the links to some papers that I read during the working of this project.

Here are the links for some of the related research papers on the supervised methods:
1. https://www.researchgate.net/publication/346184474_A_Real-time_Risk_Assessment_for_Information_System_with_CICIDS2017_Dataset_Using_Machine_Learning
2. https://arxiv.org/abs/1810.07321

Links to the supervised datasets: 
1. https://www.unb.ca/cic/datasets/ids-2017.html
2. https://www.unb.ca/cic/datasets/ids-2018.html

On the unsupervised methods:
https://ieeexplore.ieee.org/document/7079116

Unfortunately, the link to the unsupervised dataset (SCVIC-APT) is no longer accessible. 

Have a good day!

**Comment by advocs** [comment]
Thank you so much for your response. How should i get the unsupervised
dataset now?(SCVIC-APT)

**Comment by HoangNV2001** [comment]
I found the link: https://ieee-dataport.org/documents/scvic-apt-2021

**Comment by advocs** [comment]
Hi,I just wanted to ask a doubt regarding this project. Are we gonna do network data capture in this project or should we provide pcap file doing the network data capture from other tools   Sent from Mail for Windows From: Nguyễn Việt HoàngSent: 05 March 2024 22:39To: HoangNV2001/Real-time-IDSCc: aditi hr; AuthorSubject: Re: [HoangNV2001/Real-time-IDS] research paper (Issue #1) I found the link: https://ieee-dataport.org/documents/scvic-apt-2021—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by HoangNV2001** [comment]
**The system captures the real-time network flow of your device**

> Hi,I just wanted to ask a doubt regarding this project. Are we gonna do network data capture in this project or should we provide pcap file doing the network data capture from other tools   Sent from Mail for Windows From: Nguyễn Việt HoàngSent: 05 March 2024 22:39To: HoangNV2001/Real-time-IDSCc: aditi hr; AuthorSubject: Re: [HoangNV2001/Real-time-IDS] research paper (Issue #1) I found the link: [https://ieee-dataport.org/documents/scvic-apt-2021—Reply](https://ieee-dataport.org/documents/scvic-apt-2021%E2%80%94Reply) to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by advocs** [comment]
Thank you for the clarification. Can we use CICIDS2017 dataset from any of
links other than ieee?And what are we gonna use for real time network data
capturing?

**Comment by HoangNV2001** [comment]
You can find the link to the CICIDS2017 dataset at the end of this page: [https://www.unb.ca/cic/datasets/ids-2017.html](https://www.unb.ca/cic/datasets/ids-2017.html)
This system uses [Npcap](https://npcap.com/) to capture realtime network data as I have included in the Requirements of README. Our program invokes Npcap by itself to get the network data and perform analyzing, so you don't have to manually capture network data.

**Comment by advocs** [comment]
Yeah got it, thank you very much. We can use any of the available
CICIDS2017 datasets right?or from the link which u have sent. And in which
file or folder to copy those datasets in our project?

**Comment by HoangNV2001** [comment]
In this project, I have included the pretrained model. The model is already trained on CICIDS and SCVIC-APT datasets. Thus, it doesn't any dataset to run.

**Comment by advocs** [comment]
Hey , i just wanted to ask more about the project .  The destination IP is
not showing and it just shows junk values. If possible can you join the
google meet? I'll schedule it today

**Comment by advocs** [comment]
Hey do you have any apk to show the demo of how it will react to malicious
applications?
