### ISSUE TITLE
Drive Link Issues when running the jupyter notebook files to access the datasets.

### ISSUE THREAD

**Issue by kipkoech20** [HoangNV2001/Real-time-IDS#2]
Hello, can someone kindly help me over here. When running the Notebook files, the very first code i.e: 
!pip install --upgrade --no-cache-dir gdown
!gdown 1SlkctUQm439s7HcT-7im5GbTD-EofJ1V, 
I am facing an error where the drive link might be expired or needs permission for accessing: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1SlkctUQm439s7HcT-7im5GbTD-EofJ1V

but Gdown can't. Please check connections and permissions.
I need to access the data sets. How can i get them kindy?
I'll appreciate given a response. Thankyou in advance.

**Comment by MaggieGeorges** [comment]
Hello, can someone kindly help me over here. When running the Notebook files, the very first code i.e:
!pip install --upgrade --no-cache-dir gdown
!gdown 1SlkctUQm439s7HcT-7im5GbTD-EofJ1V,
I am facing an error where the drive link might be expired or needs permission for accessing: Failed to retrieve file url:

Cannot retrieve the public link of the file. You may need to change
the permission to 'Anyone with the link', or have had many accesses.
Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.
You may still be able to access the file from the browser:

https://drive.google.com/uc?id=1SlkctUQm439s7HcT-7im5GbTD-EofJ1V
but Gdown can't. Please check connections and permissions.

****
**I need to access the data sets. How can i get them kindy?
I'll appreciate given a response. Thankyou in advance.**

**Comment by HoangNV2001** [comment]
Hi. 

Unfortunately, the data files were long deleted and are no longer recoverable. 

On the other hand, we did not intend to upload the notebooks. The purpose was only to upload the application, along with the trained model. The notebooks were only for private submission to our teacher.

Sorry for the inconvenient. I hope you still find the project useful.

**Comment by HoangNV2001** [comment]
Hi.

Unfortunately, the data files were long deleted and are no longer recoverable.

On the other hand, we did not intend to upload the notebooks. The purpose was only to upload the application, along with the trained model. The notebooks were only for private submission to our teacher.

Sorry for the inconvenient. I hope you still find the project useful.

**Comment by MaggieGeorges** [comment]
This will be much helpful. Thanks alot.

**Comment by MaggieGeorges** [comment]
Hello, am sorry for distrbing, i want to get a better understanding about the project. Is it detecting intrusions all over the world? Or maybe could you have a documentation that i could go through, kindly.

Thankyou in advance for your time and consideration.

**Comment by HoangNV2001** [comment]
This program _captures the network flow of the device that it is running on in real-time_ and analyze them. The analyzing includes classification of known attacks from CICIDS dataset using a pretrained supervised Random Forest model, and anomaly detection using an Auto Encoder model.

**Comment by MaggieGeorges** [comment]
Thankyou
